/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayerIndexRouteImport } from './routes/player.index'
import { Route as PlayerPlaylistIdRouteImport } from './routes/player.$playlistId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerIndexRoute = PlayerIndexRouteImport.update({
  id: '/player/',
  path: '/player/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerPlaylistIdRoute = PlayerPlaylistIdRouteImport.update({
  id: '/player/$playlistId',
  path: '/player/$playlistId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/player/$playlistId': typeof PlayerPlaylistIdRoute
  '/player/': typeof PlayerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/player/$playlistId': typeof PlayerPlaylistIdRoute
  '/player': typeof PlayerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/player/$playlistId': typeof PlayerPlaylistIdRoute
  '/player/': typeof PlayerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/player/$playlistId' | '/player/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/player/$playlistId' | '/player'
  id: '__root__' | '/' | '/player/$playlistId' | '/player/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlayerPlaylistIdRoute: typeof PlayerPlaylistIdRoute
  PlayerIndexRoute: typeof PlayerIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/': {
      id: '/player/'
      path: '/player'
      fullPath: '/player/'
      preLoaderRoute: typeof PlayerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$playlistId': {
      id: '/player/$playlistId'
      path: '/player/$playlistId'
      fullPath: '/player/$playlistId'
      preLoaderRoute: typeof PlayerPlaylistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlayerPlaylistIdRoute: PlayerPlaylistIdRoute,
  PlayerIndexRoute: PlayerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
