/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteRouteImport } from './routes/index/route'
import { Route as PlayerPlaylistIdRouteRouteImport } from './routes/player/$playlistId/route'
import { Route as PlayerIndexRouteRouteImport } from './routes/player/index/route'

const IndexRouteRoute = IndexRouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerPlaylistIdRouteRoute = PlayerPlaylistIdRouteRouteImport.update({
  id: '/player/$playlistId',
  path: '/player/$playlistId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerIndexRouteRoute = PlayerIndexRouteRouteImport.update({
  id: '/player/',
  path: '/player',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRouteRoute
  '/player/': typeof PlayerIndexRouteRoute
  '/player/$playlistId': typeof PlayerPlaylistIdRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRouteRoute
  '/player': typeof PlayerIndexRouteRoute
  '/player/$playlistId': typeof PlayerPlaylistIdRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRouteRoute
  '/player/': typeof PlayerIndexRouteRoute
  '/player/$playlistId': typeof PlayerPlaylistIdRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/player/' | '/player/$playlistId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/player' | '/player/$playlistId'
  id: '__root__' | '/' | '/player/' | '/player/$playlistId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRouteRoute: typeof IndexRouteRoute
  PlayerIndexRouteRoute: typeof PlayerIndexRouteRoute
  PlayerPlaylistIdRouteRoute: typeof PlayerPlaylistIdRouteRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$playlistId': {
      id: '/player/$playlistId'
      path: '/player/$playlistId'
      fullPath: '/player/$playlistId'
      preLoaderRoute: typeof PlayerPlaylistIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/': {
      id: '/player/'
      path: '/player'
      fullPath: '/player/'
      preLoaderRoute: typeof PlayerIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRouteRoute: IndexRouteRoute,
  PlayerIndexRouteRoute: PlayerIndexRouteRoute,
  PlayerPlaylistIdRouteRoute: PlayerPlaylistIdRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
