name: CI

on:
  pull_request:
  push:
    branches: [main]

permissions: {}

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      # v6
      - uses: actions/checkout@v6

      # v4
      - uses: pnpm/action-setup@v4

      #v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24.12.0
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm run fmt:ci
